version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: express-api
    ports:
      - "8000:8000" # Assuming Express listens on 8000
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./client
    container_name: react-app
    ports:
      - "3000:3000"  # React dev server
    environment:
      - NODE_ENV=development
    restart: unless-stopped
