services:
  - type: web
    name: exercisedb-frontend
    env: docker
    repo: https://github.com/khushi830/Ecercise_DB
    rootDir: client
    plan: free
    autoDeploy: true
    envVars:
      - fromGroup: exercisedb-frontend-env

  - type: web
    name: exercisedb-backend
    env: docker
    repo: https://github.com/khushi830/Ecercise_DB
    rootDir: server
    plan: free
    autoDeploy: true
    envVars:
      - fromGroup: exercisedb-backend-env
