services:
  - type: web
    name: express-api
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true

  - type: web
    name: react-app
    env: static
    rootDir: frontend
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: build
    autoDeploy: true
